"use client";

import { motion, useScroll, useMotionValueEvent, AnimatePresence } from "motion/react";
import { useRef, useState } from "react";

/* --------------------------------------------------------------------------
   ALPHA · PROCESS FLOW DIAGRAM (PFD-001)
   Scroll-constructed technical drawing.
   The diagram completes itself through four chapters as the user scrolls.
-------------------------------------------------------------------------- */

const PHASES = [
  {
    key: "input",
    numeral: "I",
    title: "Input",
    caption:
      "Industrial waste arrives at site under contract. Approximately 180 tonnes per month — the hazardous, chromium-bearing fraction generated by stainless-steel finishing.",
  },
  {
    key: "segregation",
    numeral: "II",
    title: "Segregation",
    caption:
      "Stream S01 enters Segregator A-100. Fine metal particles separate out and return to the melt shop as feed (S05). The residue stream S02 advances to recovery.",
  },
  {
    key: "process",
    numeral: "III",
    title: "Recovery & Hydrometallurgy",
    caption:
      "Recovery A-200 separates metal from oxide-bearing dust. Hydrometallurgy A-300 extracts gypsum, sodium sulphate, and metal-oxide powders as distinct streams.",
  },
  {
    key: "balance",
    numeral: "IV",
    title: "Bricks & Mass Balance",
    caption:
      "Residual fines pass to Brick Plant A-400 — cement-less bricks at 19–20 kg/sq mm. Mass balance closes at 100 %. No stream leaves the site as residue.",
  },
];

const FOREST = "#0E2F23";
const SAGE = "#4A7C4E";
const LINE = "#D5CFBC";
const PAPER = "#F5F1E8";

export default function Cinematic() {
  const ref = useRef<HTMLElement>(null);
  const [activePhase, setActivePhase] = useState(0);
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ["start start", "end end"],
  });

  useMotionValueEvent(scrollYProgress, "change", (v) => {
    const idx = Math.min(PHASES.length - 1, Math.max(0, Math.floor(v * PHASES.length)));
    if (idx !== activePhase) setActivePhase(idx);
  });

  return (
    <section ref={ref} className="relative" style={{ height: "500vh" }}>
      <div className="sticky top-0 h-screen overflow-hidden bg-paper">
        <BlueprintGrid />
        <div className="absolute inset-0 grain opacity-30 pointer-events-none" />
        <CornerMarks />
        <TitleBlock activePhase={activePhase} />
        <RevisionStamp activePhase={activePhase} />

        <div className="absolute inset-0 grid place-items-center pt-12 pb-44 px-4">
          <PFD activePhase={activePhase} />
        </div>

        <ProgressBar activePhase={activePhase} />
        <Captions activePhase={activePhase} />
      </div>
    </section>
  );
}

/* ---------- Layout chrome (the "drawing" frame) ------------------------- */

function BlueprintGrid() {
  return (
    <svg
      className="absolute inset-0 w-full h-full pointer-events-none"
      preserveAspectRatio="none"
    >
      <defs>
        <pattern id="grid-fine" width="20" height="20" patternUnits="userSpaceOnUse">
          <path d="M 20 0 L 0 0 0 20" fill="none" stroke={LINE} strokeWidth="0.4" opacity="0.55" />
        </pattern>
        <pattern id="grid-coarse" width="100" height="100" patternUnits="userSpaceOnUse">
          <path d="M 100 0 L 0 0 0 100" fill="none" stroke={LINE} strokeWidth="0.6" opacity="0.7" />
        </pattern>
      </defs>
      <rect width="100%" height="100%" fill="url(#grid-fine)" />
      <rect width="100%" height="100%" fill="url(#grid-coarse)" />
    </svg>
  );
}

function CornerMarks() {
  return (
    <>
      {/* Four corner crosshairs — drawing-frame style */}
      {[
        { top: 16, left: 16, rot: 0 },
        { top: 16, right: 16, rot: 90 },
        { bottom: 16, left: 16, rot: -90 },
        { bottom: 16, right: 16, rot: 180 },
      ].map((c, i) => (
        <div
          key={i}
          style={{
            position: "absolute",
            top: c.top,
            bottom: c.bottom,
            left: c.left,
            right: c.right,
            transform: `rotate(${c.rot}deg)`,
            width: 28,
            height: 28,
          }}
          className="pointer-events-none"
        >
          <svg viewBox="0 0 28 28" className="w-full h-full">
            <line x1="0" y1="0" x2="14" y2="0" stroke={FOREST} strokeWidth="1.2" />
            <line x1="0" y1="0" x2="0" y2="14" stroke={FOREST} strokeWidth="1.2" />
          </svg>
        </div>
      ))}
    </>
  );
}

function TitleBlock({ activePhase }: { activePhase: number }) {
  return (
    <div className="absolute top-6 left-8 right-8 z-20 flex items-center justify-between text-[10px] font-mono uppercase tracking-[0.28em] text-forest pointer-events-none">
      <div className="flex items-center gap-4">
        <span>Alpha · Waste Management</span>
        <span className="opacity-50">/</span>
        <span>PFD-001</span>
        <span className="opacity-50">/</span>
        <span>Rev. 0</span>
      </div>
      <div className="hidden sm:flex items-center gap-4">
        <span>Sheet 01 of 01</span>
        <span className="opacity-50">/</span>
        <span>Scale n.t.s.</span>
      </div>
    </div>
  );
}

function RevisionStamp({ activePhase }: { activePhase: number }) {
  return (
    <div className="absolute bottom-6 left-8 z-20 flex flex-col gap-1 text-[10px] font-mono uppercase tracking-[0.28em] text-forest/80 pointer-events-none">
      <div className="flex items-center gap-3">
        <span className="inline-block w-2 h-2 border border-forest" />
        <span>
          Drafted from process documentation · {String(activePhase + 1).padStart(2, "0")} of 04 chapters
        </span>
      </div>
    </div>
  );
}

function ProgressBar({ activePhase }: { activePhase: number }) {
  return (
    <div className="absolute top-20 sm:top-24 left-1/2 -translate-x-1/2 z-30">
      <div className="flex items-center gap-2 sm:gap-3">
        {PHASES.map((p, i) => (
          <motion.div
            key={p.key}
            animate={{ opacity: i === activePhase ? 1 : 0.35 }}
            transition={{ duration: 0.4 }}
            className="flex items-center gap-2 sm:gap-3"
          >
            <span className="text-[10px] sm:text-xs font-mono uppercase tracking-[0.28em] text-forest">
              {p.numeral}
            </span>
            {i < PHASES.length - 1 && (
              <span className="h-px w-4 sm:w-10 bg-forest/30" />
            )}
          </motion.div>
        ))}
      </div>
    </div>
  );
}

function Captions({ activePhase }: { activePhase: number }) {
  const phase = PHASES[activePhase];
  return (
    <div className="absolute bottom-16 sm:bottom-20 left-0 right-0 z-30 px-8">
      <div className="mx-auto max-w-3xl relative h-32 sm:h-28">
        <AnimatePresence mode="wait">
          <motion.div
            key={phase.key}
            initial={{ opacity: 0, y: 16 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -16 }}
            transition={{ duration: 0.45, ease: [0.16, 1, 0.3, 1] }}
            className="absolute inset-0"
          >
            <div className="flex items-center gap-3 text-[10px] font-mono uppercase tracking-[0.28em] text-forest">
              <span className="border border-forest px-1.5 py-0.5">
                Chapter {phase.numeral}
              </span>
              <span className="opacity-60">{phase.title}</span>
            </div>
            <p className="mt-3 text-[13px] sm:text-base text-graphite leading-relaxed max-w-2xl">
              {phase.caption}
            </p>
          </motion.div>
        </AnimatePresence>
      </div>
    </div>
  );
}

/* ---------- The PFD itself ---------------------------------------------- */

function PFD({ activePhase }: { activePhase: number }) {
  return (
    <svg
      viewBox="0 0 1200 600"
      preserveAspectRatio="xMidYMid meet"
      className="w-full max-w-[1400px] h-full max-h-[65vh]"
    >
      <defs>
        <marker
          id="arrow"
          viewBox="0 0 10 10"
          refX="9"
          refY="5"
          markerUnits="strokeWidth"
          markerWidth="6"
          markerHeight="6"
          orient="auto"
        >
          <path d="M 0 0 L 10 5 L 0 10 Z" fill={FOREST} />
        </marker>
        <marker
          id="arrow-sage"
          viewBox="0 0 10 10"
          refX="9"
          refY="5"
          markerUnits="strokeWidth"
          markerWidth="6"
          markerHeight="6"
          orient="auto"
        >
          <path d="M 0 0 L 10 5 L 0 10 Z" fill={SAGE} />
        </marker>
      </defs>

      {/* Internal axis ticks */}
      <AxisTicks />

      {/* Phase 1 — Input source + S01 */}
      <InputSource visible={activePhase >= 0} />
      <Stream
        id="S01"
        d="M 168 240 L 296 240"
        label="Industrial waste"
        sublabel="~180 MT/mo · hazardous"
        visible={activePhase >= 0}
      />

      {/* Phase 2 — Segregator + outputs */}
      <Equipment
        id="A-100"
        title="Segregator"
        x={300}
        y={196}
        w={140}
        h={88}
        visible={activePhase >= 1}
      />
      <Stream
        id="S02"
        d="M 444 240 L 564 240"
        label="Residue"
        sublabel="oxide + metal dust"
        visible={activePhase >= 1}
        delay={0.4}
      />
      <Stream
        id="S05"
        d="M 370 196 L 370 100 L 1080 100"
        label="Metal fines"
        sublabel="→ melt shop"
        labelX={720}
        labelY={84}
        visible={activePhase >= 1}
        delay={0.6}
        color="sage"
      />
      <Terminal x={1080} y={100} label="MELT SHOP" visible={activePhase >= 1} delay={0.9} variant="sage" />

      {/* Phase 3 — Recovery + Hydromet + outputs */}
      <Equipment
        id="A-200"
        title="Recovery"
        x={566}
        y={196}
        w={140}
        h={88}
        visible={activePhase >= 2}
      />
      <Stream
        id="S03"
        d="M 710 240 L 818 240"
        label="Recovered metal"
        sublabel="& mixed oxides"
        visible={activePhase >= 2}
        delay={0.4}
      />
      <Equipment
        id="A-300"
        title="Hydrometallurgy"
        x={820}
        y={196}
        w={140}
        h={88}
        visible={activePhase >= 2}
        delay={0.5}
      />
      <Stream
        id="S06"
        d="M 964 220 L 1080 220"
        label="Gypsum"
        sublabel="CaSO₄"
        visible={activePhase >= 2}
        delay={0.8}
      />
      <Stream
        id="S07"
        d="M 964 240 L 1080 240"
        label="Sodium sulphate"
        sublabel="Na₂SO₄"
        visible={activePhase >= 2}
        delay={0.9}
        labelY={272}
      />
      <Stream
        id="S08"
        d="M 964 260 L 1080 260"
        label="Metal oxides"
        sublabel="Fe₂O₃ · Cr₂O₃ · NiO"
        visible={activePhase >= 2}
        delay={1.0}
        labelY={296}
      />
      <Terminal x={1080} y={220} label="SALEABLE OUTPUTS · S06–S08" visible={activePhase >= 2} delay={1.2} bigHeight={84} />

      {/* Phase 4 — Brick plant + bricks output */}
      <Stream
        id="S04"
        d="M 890 284 L 890 380"
        label="Slag · fines"
        sublabel=""
        visible={activePhase >= 3}
        labelX={910}
        labelY={336}
      />
      <Equipment
        id="A-400"
        title="Brick Plant"
        x={820}
        y={380}
        w={140}
        h={88}
        visible={activePhase >= 3}
        delay={0.3}
      />
      <Stream
        id="S09"
        d="M 964 424 L 1080 424"
        label="Cement-less bricks"
        sublabel="19–20 kg/sq mm"
        visible={activePhase >= 3}
        delay={0.6}
      />
      <Terminal x={1080} y={424} label="BRICKS · S09" visible={activePhase >= 3} delay={0.8} variant="rust" />

      {/* Mass balance stamp - phase 4 */}
      <MassBalanceStamp visible={activePhase >= 3} />
    </svg>
  );
}

/* ---------- Diagram primitives ------------------------------------------ */

function AxisTicks() {
  const ticks = [];
  for (let x = 0; x <= 1200; x += 100) {
    ticks.push(
      <g key={`x-${x}`}>
        <line x1={x} y1={4} x2={x} y2={10} stroke={FOREST} strokeWidth="0.5" opacity="0.35" />
        <line x1={x} y1={590} x2={x} y2={596} stroke={FOREST} strokeWidth="0.5" opacity="0.35" />
        {x % 200 === 0 && (
          <>
            <text x={x} y={18} fontSize="7" fill={FOREST} opacity="0.5" fontFamily="ui-monospace, monospace" textAnchor="middle">
              {x}
            </text>
            <text x={x} y={584} fontSize="7" fill={FOREST} opacity="0.5" fontFamily="ui-monospace, monospace" textAnchor="middle">
              {x}
            </text>
          </>
        )}
      </g>
    );
  }
  for (let y = 0; y <= 600; y += 100) {
    ticks.push(
      <g key={`y-${y}`}>
        <line x1={4} y1={y} x2={10} y2={y} stroke={FOREST} strokeWidth="0.5" opacity="0.35" />
        <line x1={1190} y1={y} x2={1196} y2={y} stroke={FOREST} strokeWidth="0.5" opacity="0.35" />
        {y % 200 === 0 && y > 0 && (
          <>
            <text x={22} y={y + 2} fontSize="7" fill={FOREST} opacity="0.5" fontFamily="ui-monospace, monospace" textAnchor="middle">
              {y}
            </text>
            <text x={1178} y={y + 2} fontSize="7" fill={FOREST} opacity="0.5" fontFamily="ui-monospace, monospace" textAnchor="middle">
              {y}
            </text>
          </>
        )}
      </g>
    );
  }
  return <g>{ticks}</g>;
}

function InputSource({ visible }: { visible: boolean }) {
  return (
    <motion.g
      initial={{ opacity: 0 }}
      animate={{ opacity: visible ? 1 : 0 }}
      transition={{ duration: 0.5 }}
    >
      <rect
        x={48}
        y={196}
        width={120}
        height={88}
        fill="none"
        stroke={FOREST}
        strokeWidth="1.5"
        strokeDasharray="3 3"
      />
      <text
        x={108}
        y={236}
        textAnchor="middle"
        fontSize="11"
        fontFamily="ui-monospace, monospace"
        letterSpacing="2"
        fill={FOREST}
      >
        INPUT
      </text>
      <text
        x={108}
        y={252}
        textAnchor="middle"
        fontSize="9"
        fontFamily="ui-monospace, monospace"
        letterSpacing="1.4"
        fill={FOREST}
        opacity="0.7"
      >
        SOURCE
      </text>
      {/* Source tag */}
      <circle cx={48} cy={196} r="9" fill={PAPER} stroke={FOREST} strokeWidth="1.2" />
      <text x={48} y={199} textAnchor="middle" fontSize="8" fontFamily="ui-monospace, monospace" fill={FOREST}>
        I
      </text>
    </motion.g>
  );
}

interface EquipmentProps {
  id: string;
  title: string;
  x: number;
  y: number;
  w: number;
  h: number;
  visible: boolean;
  delay?: number;
}

function Equipment({ id, title, x, y, w, h, visible, delay = 0.1 }: EquipmentProps) {
  return (
    <motion.g
      initial={{ opacity: 0, scale: 0.94 }}
      animate={{ opacity: visible ? 1 : 0, scale: visible ? 1 : 0.94 }}
      transition={{ duration: 0.55, delay: visible ? delay : 0, ease: [0.16, 1, 0.3, 1] }}
      style={{ transformOrigin: `${x + w / 2}px ${y + h / 2}px` }}
    >
      {/* Double-line border — PFD convention for processing equipment */}
      <rect x={x} y={y} width={w} height={h} fill={PAPER} stroke={FOREST} strokeWidth="1.5" />
      <rect x={x + 4} y={y + 4} width={w - 8} height={h - 8} fill="none" stroke={FOREST} strokeWidth="0.6" />
      {/* Tag circle */}
      <circle cx={x + 16} cy={y + 16} r="11" fill={PAPER} stroke={FOREST} strokeWidth="1.2" />
      <text x={x + 16} y={y + 19} textAnchor="middle" fontSize="8" fontFamily="ui-monospace, monospace" fill={FOREST}>
        {id.split("-")[1]}
      </text>
      {/* Title */}
      <text
        x={x + w / 2}
        y={y + h / 2 + 4}
        textAnchor="middle"
        fontSize="13"
        fontFamily="ui-monospace, monospace"
        letterSpacing="2"
        fill={FOREST}
      >
        {title.toUpperCase()}
      </text>
      <text
        x={x + w / 2}
        y={y + h - 12}
        textAnchor="middle"
        fontSize="8"
        fontFamily="ui-monospace, monospace"
        letterSpacing="1.4"
        fill={FOREST}
        opacity="0.6"
      >
        {id}
      </text>
      {/* Process indicator pulse */}
      <motion.circle
        cx={x + w - 14}
        cy={y + 14}
        r="3"
        fill={SAGE}
        animate={{ opacity: [0.4, 1, 0.4] }}
        transition={{ duration: 1.8, repeat: Infinity, ease: "easeInOut" }}
      />
    </motion.g>
  );
}

interface StreamProps {
  id: string;
  d: string;
  label: string;
  sublabel: string;
  visible: boolean;
  delay?: number;
  labelX?: number;
  labelY?: number;
  color?: "forest" | "sage";
}

function Stream({ id, d, label, sublabel, visible, delay = 0.2, labelX, labelY, color = "forest" }: StreamProps) {
  // Auto-derive label position from path midpoint if not specified
  const stroke = color === "sage" ? SAGE : FOREST;
  const marker = color === "sage" ? "url(#arrow-sage)" : "url(#arrow)";

  return (
    <motion.g
      initial={{ opacity: 0 }}
      animate={{ opacity: visible ? 1 : 0 }}
      transition={{ duration: 0.3 }}
    >
      <motion.path
        d={d}
        stroke={stroke}
        strokeWidth="1.5"
        fill="none"
        markerEnd={marker}
        initial={{ pathLength: 0 }}
        animate={{ pathLength: visible ? 1 : 0 }}
        transition={{ duration: 0.9, delay: visible ? delay : 0, ease: [0.16, 1, 0.3, 1] }}
      />
      {/* Stream tag - diamond */}
      <StreamTag
        id={id}
        path={d}
        delay={delay + 0.6}
        visible={visible}
        color={color}
        x={labelX}
        y={labelY}
      />
      <StreamLabel
        path={d}
        label={label}
        sublabel={sublabel}
        delay={delay + 0.7}
        visible={visible}
        x={labelX}
        y={labelY}
      />
    </motion.g>
  );
}

function StreamTag({
  id,
  path,
  delay,
  visible,
  color,
  x,
  y,
}: {
  id: string;
  path: string;
  delay: number;
  visible: boolean;
  color: "forest" | "sage";
  x?: number;
  y?: number;
}) {
  const stroke = color === "sage" ? SAGE : FOREST;
  // Estimate diamond position from start of path
  const m = path.match(/M\s*([\d.]+)\s+([\d.]+)/);
  const tx = x ?? (m ? parseFloat(m[1]) + 22 : 0);
  const ty = y ?? (m ? parseFloat(m[2]) - 12 : 0);
  return (
    <motion.g
      initial={{ opacity: 0 }}
      animate={{ opacity: visible ? 1 : 0 }}
      transition={{ duration: 0.4, delay: visible ? delay : 0 }}
    >
      <polygon
        points={`${tx},${ty - 8} ${tx + 16},${ty} ${tx},${ty + 8} ${tx - 16},${ty}`}
        fill={PAPER}
        stroke={stroke}
        strokeWidth="1"
      />
      <text x={tx} y={ty + 3} textAnchor="middle" fontSize="8" fontFamily="ui-monospace, monospace" fill={stroke}>
        {id}
      </text>
    </motion.g>
  );
}

function StreamLabel({
  path,
  label,
  sublabel,
  delay,
  visible,
  x,
  y,
}: {
  path: string;
  label: string;
  sublabel: string;
  delay: number;
  visible: boolean;
  x?: number;
  y?: number;
}) {
  // Estimate label position near path end
  const matches = Array.from(path.matchAll(/([\d.]+)\s+([\d.]+)/g)).map((m) => [
    parseFloat(m[1]),
    parseFloat(m[2]),
  ]);
  const start = matches[0] ?? [0, 0];
  const end = matches[matches.length - 1] ?? [0, 0];
  const mx = x ?? (start[0] + end[0]) / 2;
  const my = y ?? Math.min(start[1], end[1]) - 8;

  return (
    <motion.g
      initial={{ opacity: 0 }}
      animate={{ opacity: visible ? 1 : 0 }}
      transition={{ duration: 0.4, delay: visible ? delay : 0 }}
    >
      <text x={mx} y={my} textAnchor="middle" fontSize="10" fontFamily="ui-monospace, monospace" letterSpacing="1.4" fill={FOREST}>
        {label.toUpperCase()}
      </text>
      {sublabel && (
        <text x={mx} y={my + 11} textAnchor="middle" fontSize="8" fontFamily="ui-monospace, monospace" letterSpacing="1.2" fill={FOREST} opacity="0.65">
          {sublabel}
        </text>
      )}
    </motion.g>
  );
}

function Terminal({
  x,
  y,
  label,
  visible,
  delay = 0.2,
  variant = "forest",
  bigHeight,
}: {
  x: number;
  y: number;
  label: string;
  visible: boolean;
  delay?: number;
  variant?: "forest" | "sage" | "rust";
  bigHeight?: number;
}) {
  const stroke = variant === "rust" ? "#8B4A2A" : variant === "sage" ? SAGE : FOREST;
  const h = bigHeight ?? 32;
  return (
    <motion.g
      initial={{ opacity: 0, x: -8 }}
      animate={{ opacity: visible ? 1 : 0, x: 0 }}
      transition={{ duration: 0.5, delay: visible ? delay : 0 }}
    >
      <rect x={x} y={y - h / 2} width={108} height={h} fill={PAPER} stroke={stroke} strokeWidth="1.2" />
      <text
        x={x + 54}
        y={y + 3}
        textAnchor="middle"
        fontSize="9"
        fontFamily="ui-monospace, monospace"
        letterSpacing="1.8"
        fill={stroke}
      >
        {label}
      </text>
    </motion.g>
  );
}

function MassBalanceStamp({ visible }: { visible: boolean }) {
  return (
    <motion.g
      initial={{ opacity: 0, scale: 0.85 }}
      animate={{ opacity: visible ? 1 : 0, scale: visible ? 1 : 0.85 }}
      transition={{ duration: 0.6, delay: visible ? 1.0 : 0, ease: [0.16, 1, 0.3, 1] }}
      style={{ transformOrigin: "200px 480px" }}
    >
      <rect x={48} y={448} width={300} height={88} fill="none" stroke={FOREST} strokeWidth="1.5" />
      <rect x={52} y={452} width={292} height={80} fill="none" stroke={FOREST} strokeWidth="0.6" />
      <text x={198} y={476} textAnchor="middle" fontSize="10" fontFamily="ui-monospace, monospace" letterSpacing="2.5" fill={FOREST}>
        MASS BALANCE CERTIFICATE
      </text>
      <text x={198} y={500} textAnchor="middle" fontSize="22" fontFamily="ui-serif, Georgia" fill={FOREST}>
        100 % closed loop
      </text>
      <text x={198} y={520} textAnchor="middle" fontSize="9" fontFamily="ui-monospace, monospace" letterSpacing="1.6" fill={FOREST} opacity="0.7">
        Σ outputs = Σ inputs · zero residue
      </text>
    </motion.g>
  );
}
